### PR TITLE
Fixed the highlighting of the selected text in edit mode #83

### PR DESCRIPTION
**Pull request by metavinayak**
Please suggest any changes required.

Screenshot from 2021-10-03 19-02-39
Screenshot from 2021-10-03 19-02-50

### CODE REVIEW

**Comment by Signior-X** [comment]
Great @metavinayak can you also see that not only the background. But the text selected is also highlighted with white.
As you see in case of preview, the color of text looks more white that really looks good.

As I have made some changes to this PR, you can fetch that also. If you face any problem, do ask.

**Comment by metavinayak** [comment]
> Great @metavinayak can you also see that not only the background. But the text selected is also highlighted with white. As you see in case of preview, the color of text looks more white that really looks good.
> 
> As I have made some changes to this PR, you can fetch that also. If you face any problem, do ask.

Sure I'll do it after fetching.

**Comment by metavinayak** [comment]
@Signior-X  pls verify https://github.com/devzes/pnotes/pull/93/commits/96796c3ddac43f542ed950bfb206e04ea84d920d

Old:
Screenshot from 2021-10-03 19-02-39

New:
Screenshot from 2021-10-03 22-36-38

**Comment by Signior-X** [comment]
Thanks for this one @metavinayak 
Nice and simple PR.

**Pull request merged**
